### ISSUE TITLE
[Question]  Asking about the API proxy

### ISSUE THREAD

**Issue by hilmanski** [maximilianschmitt/next-auth#5]
Hi @maximilianschmitt  thanks for your article about [httponly cookie implementation](https://maxschmitt.me/posts/next-js-http-only-cookie-auth-tokens/) .

I have a question regarding the API proxy.

If we build our own API from scratch, 
1. should we still add the proxy layer? 
since the caveat will be extra code for whole route again on the "SPA layer server"

2. Or just implement the httponly cookie directly on the "original server"
Assume, CORS is not an issue. Or does it impossible if it's on different domain?

thanks again for your article

**Comment by maximilianschmitt** [comment]
Hi @hilmanski!

I would say that if you have the option to implement cookie-based auth in your API directly, then that will be the faster way to go. :) From a quick research it seems like you just need to make sure that your API is served on the same domain or a subdomain, otherwise you can run into issues with third-party-cookies being blocked.

Hope that helps!

Max
