### ISSUE TITLE
protected routes

### ISSUE THREAD

**Issue by Mood-al** [maximilianschmitt/next-auth#6]
Hey guys do you have any idea how we can implement protected routes in next js ??

for now im handling it by using getServerSideProps like this 

![image](https://user-images.githubusercontent.com/63562308/141707417-033abd2d-c824-4690-be65-3e75d3b5a295.png)

so do you have any idea if there is any better way to handle it for certain pages ?
and thank you so much for this example it helped me a lot with my project

**Comment by maximilianschmitt** [comment]
Hi @Mood-al,

I would recommend asking the API for the login state. The presence of a cookie is not enough, since that cookie can hold an invalid token.

Check this for an example: https://github.com/maximilianschmitt/next-auth/blob/6d9ea5ce9b3c43071439806a0b1d954cd4717f94/pages/index.js#L16-L30

Hope that helps!
