### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by richardantao** [maximilianschmitt/next-auth#7]
Hello. After cloning the repo, when I attempt to simulate a login I get the following error:

```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.eval (webpack-internal:///./pages/api/proxy/[...path].js:47:22)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I haven't changed anything in the repo other than using npm instead of yarn. Any thoughts on why this error is occurring?

**Comment by richardantao** [comment]
Looks like it's the `const { authToken } = JSON.parse(responseBody)` line in the code below:

```
proxy.once('proxyRes', (proxyRes, req, res) => {
	  let responseBody = ''
	  proxyRes.on('data', (chunk) => {
	    responseBody += chunk
	  })
	  proxyRes.on('end', () => {
	    const { authToken } = JSON.parse(responseBody)
	  })
  })
```

`JSON.parse(responseBody)` returns the error because if you inspect `responseBody`, the Buffer/string is all gibberish. I suspect this has something to do with compression?

**Comment by maximilianschmitt** [comment]
Hi @richardantao, I've just tried it and the code still works. I also just upgraded the packages in the repo to use latest Next.js, React and ReactDOM.

Are you running the app using `yarn dev`? If not, try setting this environment variable:

```
API_URL=http://localhost:3000/api
```

I think the `chunk` you receive in the data event might be a buffer. You can try stringifying it to get some insight into what kind of data it contains:

```
proxyRes.on('data', (chunk) => {
	console.log(chunk.toString('utf8'))
	responseBody += chunk
})
```

I'm closing the issue for now since it's a little bit old. Please feel free to reopen if you're still having problems!
