### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by yogip07** [maximilianschmitt/next-auth#9]
Can we just use middleware, instead of make a proxy servers?

**Comment by KoolP** [comment]
Could that make it simpler? I was also thinking of this, but is the idea of proxy server to abstract the use to include in api folder instead of all requests. I mean for example in Next JS the middleware seems to run even when calling page routes. It sits in the root of the project but this sits in the api folder.

**Comment by yogip07** [comment]
ohh i see
